# NOTE: This file has been moved to the project root for correct .env and path resolution.
services:
  frontend:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_LOCK: ${NEXT_PUBLIC_SUPABASE_ANON_LOCK}
    image: biobank-frontend:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_LOCK: ${NEXT_PUBLIC_SUPABASE_ANON_LOCK}