# NOTE: This file has been moved to the project root for correct .env and path resolution.
services:
  frontend:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: ${FRONTEND_TARGET:-development}  # Use development by default, can be overridden with FRONTEND_TARGET=production
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_LOCK: ${NEXT_PUBLIC_SUPABASE_ANON_LOCK}
    image: biobank-frontend:${FRONTEND_TARGET:-development}
    ports:
      - "3000:3000"
    volumes:
      # Mount the frontend directory for hot reloading in development mode
      - ./frontend:/app:delegated
      # Prevent node_modules from being overwritten by the host
      - /app/node_modules
    environment:
      NODE_ENV: ${FRONTEND_TARGET:-development}
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_LOCK: ${NEXT_PUBLIC_SUPABASE_ANON_LOCK}