# NOTE: This file has been moved to the project root for correct .env and path resolution.
services:
  frontend:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    image: biobank-frontend:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    depends_on:
      - backend

  backend:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        SUPABASE_URL: ${SUPABASE_URL}
        SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
        NEO4J_URI: ${NEO4J_URI}
        NEO4J_USER: ${NEO4J_USER}
        NEO4J_PASSWORD: ${NEO4J_PASSWORD}
        API_KEY: ${API_KEY}
    image: biobank-backend:latest
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      NEO4J_URI: ${NEO4J_URI}
      NEO4J_USER: ${NEO4J_USER}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      API_KEY: ${API_KEY}
    depends_on:
      - supabase
      - neo4j

  supabase:
    env_file: .env
    image: supabase/postgres:15.1.0.116
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${SUPABASE_DB_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - supabase-data:/var/lib/postgresql/data

  neo4j:
    env_file: .env
    image: neo4j:5.15
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "${NEO4J_USER}/${NEO4J_PASSWORD}"
    volumes:
      - neo4j-data:/data

volumes:
  supabase-data:
    driver: local
  neo4j-data:
    driver: local