# ==================================================================================================
# CENTRALIZED CONTAINER/SERVICE CONFIGURATION
# This file is the single source of truth for all container and service parameters used in Dockerfiles
# and docker-compose.yml. All secrets must be referenced via environment variables.
# ==================================================================================================

version: "1.0.0"
last_updated: "2025-04-18"
author: "config-manager"
description: |
  Defines all container/service parameters for the Next.js frontend.
  No hardcoded secrets. All values are referenced by Dockerfiles and docker-compose.yml.
  Update this file before making any changes to container/service configuration.

services:
  frontend:
    name: "frontend"
    image: "biobank-frontend:latest"
    build_context: "./frontend"
    dockerfile: "Dockerfile.frontend"
    ports:
      - 3000:3000  # host:container
    env:
      NODE_ENV: "development"
      NEXT_PUBLIC_SUPABASE_URL: "${NEXT_PUBLIC_SUPABASE_URL}"         # from .env or deployment env
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "${NEXT_PUBLIC_SUPABASE_ANON_KEY}" # from .env or deployment env
      # Add other public env vars as needed
    resource_limits:
      cpus: "0.5"
      memory: "512m"

# All secrets must be provided via environment variables (.env for local, Vercel/CI for prod)
# Do not hardcode any sensitive values here.